export const INCREMENTE = 'INCREMENTE';
export const DECREMENTE = 'DECREMENTE';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';

export const SET_PSEUDO_FRIEND = 'SET_PSEUDO_FRIEND';
export const TOGGLE_MENU = 'TOGGLE_MENU';
export const SET_ETUDIANT = 'SET_ETUDIANT';
export const SET_WEATHER = 'SET_WEATHER';
export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_ENSEIGNANTS = 'SET_ENSEIGNANTS';
export const SET_ENSEIGNANTS_FILTER = 'SET_ENSEIGNANTS_FILTER';
export const SET_REPAS = 'SET_REPAS';
export const SET_SALLE_SELECTED = 'SET_SALLE_SELECTED';
export const SET_ETAGE_SELECTED = 'SET_ETAGE_SELECTED';
export const SET_BATIMENT_SELECTED = 'SET_BATIMENT_SELECTED';